# Generated by Django 3.0.8 on 2020-11-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence_sys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='rfid',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
